apiVersion: newide.studio.dataleap.volc/v1
kind: Pipeline
metadata:
  name: git_PT_test001
spec:
  displayName: git_PT_test001
  description: ''
  runAs: User/83306922
  trigger:
    type: SCHEDULED
    pauseStatus: UNPAUSED
    frequency: daily
    cronExpression: 01 00 * * *
    priority: d5
  activities:
    - name: git_PT_test001
      type: notebook
      source: WORKSPACE
      path: /Workspace/User/liheng.uszl-83306922/B_test.ipynb
      kernelType: emr_serverless_spark_python
      engineQueue: dmp_emr_queue-Default
      sparkConf:
        - key: serverless.spark.access.key
          value: '{{AK_1}}'
        - key: serverless.spark.secret.key
          value: '{{SK_1}}'
      executeParam:
        image:
          imageUrl: >-
            emr-serverless-online-cn-beijing.cr.volces.com/emr-serverless-engine/spark:3.5.1-py3.12-ubuntu20.04-861
        cpuCores: 1
        memoryMb: 4096
      parameters: []
      resources: []
  schedulingResourceGroupName: dmp_schedule
  schedulingResourceGroupId: 1514
